### ISSUE TITLE
RuntimeError: abort(OOM). Build with -s ASSERTIONS=1 for more info

### ISSUE THREAD

**Issue by papirosko** [ukyo/lz4.js#18]
I am constantly getting this error:

```OOM
RuntimeError: abort(OOM). Build with -s ASSERTIONS=1 for more info.
    at y (/opt/docker/node_modules/lz4-asm/dist/lz4wasm.js:16:393)
    at c (/opt/docker/node_modules/lz4-asm/dist/lz4wasm.js:19:185)
    at null.<anonymous> (wasm://wasm/000583fa:1:9108)
    at null.<anonymous> (wasm://wasm/000583fa:1:5022)
    at null.<anonymous> (wasm://wasm/000583fa:1:70682)
    at null.<anonymous> (wasm://wasm/000583fa:1:89144)
    at b.L (/opt/docker/node_modules/lz4-asm/dist/lz4wasm.js:36:268)
    at b.K (/opt/docker/node_modules/lz4-asm/dist/lz4wasm.js:36:340)
    at Object.decompress (/opt/docker/node_modules/lz4-asm/dist/lz4wasm.js:41:180)
    at /opt/docker/node_modules/kafkajs-lz4/lib/index.js:37:50
```

we are running application, which process the logs, coming via kafka with lz4 encoding enabled. it keeps running for a couple of days and then just restarts with OOM. The common memory metrics doesn't show any suspicious:

<img width="349" alt="image" src="https://user-images.githubusercontent.com/1061424/213910469-f7ca20c9-69f2-41d4-ac02-fad730414d61.png">

the node was restarted with OOM at 11:40

**Comment by chenbo689** [comment]
Do you have a solution? I have also encountered it now

**Comment by papirosko** [comment]
yes. the problem is not with lz4. but logs always shows lz4 stacktrace for some strange reason.
