### ISSUE TITLE
ERROR_srcPtr_wrong in decompress for multi threads applincation

### ISSUE THREAD

**Issue by sara66** [ukyo/lz4.js#3]
I used the decompress function in a multi- theareded application and sometimes, the function is not run to the end successfuly and gives this error ERROR_srcPtr_wrong.
Is it suposed to support multithread applications?

**Comment by maksimpiriyev** [comment]
I also sometimes got this error ,
when i have compressed file in the server with other lz4 compressor and tried to decompress in the browser,
@sara66 have you found a solution for this issue ?

**Comment by Havanero** [comment]
I have the same issue at wrapSafe (internal/modules/cjs/loader.js:1072:16)
    at Module._compile (internal/modules/cjs/loader.js:1122:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Object.<anonymous> (/var/app/current/node_modules/pm2/lib/ProcessContainerFork.js:32:23)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)

**Comment by Havanero** [comment]
ash-4.2$ head err-queue.log 
Error: ERROR_srcPtr_wrong
    at Array.Ca (/var/app/current/node_modules/lz4-asm/lz4.js:27:488)
    at _emscripten_asm_const_2 (/var/app/current/node_modules/lz4-asm/lz4.js:42:345)
    at Ga (/var/app/current/node_modules/lz4-asm/lz4.js:47:11948)
    at f.g.P (/var/app/current/node_modules/lz4-asm/lz4.js:66:28)
    at f.da (/var/app/current/node_modules/lz4-asm/lz4.js:70:151)
    at u (/var/app/current/node_modules/lz4-asm/lz4.js:65:3)
    at Object.decompress (/var/app/current/node_modules/lz4-asm/lz4.js:63:392)
